settings:
  commit_msg: "Update README with actions"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "push"
    - "issues"
    - "review"
    - "star"
    - "wiki"
    - "fork"
  commit_name: "Github-Actions"
messages:
  comments: "💬 Commented in {REPO}"
  issue_opened: "❗️ Opened issue in {REPO}"
  issue_closed: "✔️ Closed issue in {REPO}"
  pr_opened: "💪 Opened PR in {REPO}"
  pr_closed: "❌ Closed PR in {REPO}"
  pr_merged: "🎉 Merged PR in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {REPO}"
  changes_requested: "🔴 Requested changes in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
